#!/bin/bash
set -e

USERNAME=pywebdriver
echo "Configure $SERVICE user and group"
if id -u $USERNAME &>/dev/null; then
    echo "$USERNAME already exists"
else
    adduser --quiet --no-create-home --system $USERNAME --quiet
    groupadd -f usbusers
    adduser $USERNAME usbusers --quiet
    adduser $USERNAME dialout --quiet
    adduser $USERNAME ssl-cert --quiet
fi

echo "Restarting udev"
if systemctl list-unit-files | grep -q '^systemd-udevd'; then
    systemctl restart systemd-udevd || true
elif systemctl list-unit-files | grep -q '^udev'; then
    systemctl restart udev || true
fi
#DEBHELPER#
